export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export const POST_FAIL = "POST_FAIL";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";

export const GET_POSTS_SEARCH_RESULTS = "GET_POSTS_SEARCH_RESULTS";

export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";

export const ADD_IMAGE = "ADD_IMAGE";
